name: MinecraftButEveryTimeYouPlaceOrBreakABlockYouLoseHalfAHeart
version: ${project.version}
main: com.gmail.nunomouraxd.minecraftbuteverytimeyouplaceorbreakablockyoulosehalfaheart.Main
api-version: 1.13
authors: [NunoMoura]
description: Minecraft but every  time you place or break a block you lose half a heart
